// Angular/src/app/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../modal/product';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit {

  constructor(private cart: CartService) { }
  cart_list : Array<Product> = [];

  total_price: number=0;

  ngOnInit(): void {
     
    if(localStorage.getItem("cart")!=null){
      this.cart.cart_list = JSON.parse(localStorage.getItem("cart") || '[]');
      this.cart_list = this.cart.cart_list;
      this.calculateBill();
      console.log(this.cart_list);
      
    }
  }

  calculateBill(){
    this.total_price = 0;
    for(let objects of this.cart_list){
      this.total_price += objects.price;
    }
  }

  removeproduct(remove : Product){
    this.cart.removeProducts(remove);
    this.calculateBill();
  }
}

<ng-container *ngIf="cart_list.length !=0">
    <div class="container" style="margin-top: 3rem;">
        <div class="card-table">
            <div class="cart-product">
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th> Name</th>
                            <th>Image</th>
                            <th>Description</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr *ngFor="let products of cart_list" id="cartList">
                            <td>{{products.name}}</td>
                            <td><img style="width: 120px;" src="{{products.imagepath}}" alt=""></td>
                            <td style="width: 25%;">{{products.description}}</td>
                            <td style="width: 12%;">{{products.quantity}}</td>
                            <th style="width: 12%;">{{products.price}}</th>
                            
                            <td>
                                <button (click)=removeproduct(products) class="btn btn-danger">Delete</button>
                            </td>
                        </tr>
                     
                    </tbody>
                </table>
                <h6 class="card-subtitle mt-2 text-end text-muted fs-5" style="color: black;margin-right:2em">
                    Total Price: <span id="total-price"> {{total_price}}</span> </h6> 
            </div>
        </div>
    </div>
    
</ng-container>


 <ng-container *ngIf="cart_list.length ==0">
    <div class="container">
       
        <div class="center">
            <h4>Your cart is empty!</h4>
            <h6>Add item to it now</h6>
            <button routerLink="/products" class="btn btn-primary">Shop Now</button>
        </div>
    </div>
</ng-container>

// React/src/cart.js
import React from 'react'
import 'bootstrap/dist/css/bootstrap.min.css';
export const Cart = (props) => {
    let cart ;
    let product ;

    if(localStorage.getItem("product") === null)
    {
        product = [];
    }
    else
    {
        product = JSON.parse(localStorage.getItem("product"));
    }
    
    
    if(localStorage.getItem("cart") === null)
    {
        cart = [];
    }
    else
    {
       cart = JSON.parse(localStorage.getItem("cart"));
    }

    const removeItems = (items) =>{
        for(let prod of product){
            if( items.productId === prod.productId  )
            {
                console.log("product",prod.productId);
                prod.quantity += parseInt(items.quantity);
                localStorage.setItem("product",JSON.stringify(product));
                console.log(product);
               
                break;
               
            }
           
        }
        cart = cart.filter(c => (c.productId !== items.productId  ));
        localStorage.setItem("cart",JSON.stringify(cart));
        props.setCarts(cart);
        
       
    }

    return (

    <div className="card" style={{"width": "100%", "margin-bottom": "20px", "margin-top": "20px", "min-height": "80%;"}}>
    <div className="card-body">
        <h1 className="card-title" style={{"text-align": "center"}}>Cart</h1>
        <div className="row">
            <div className="col-md-12">
            {
                props.cart.map((productitem) => {
                          
                                            return (
                                                <div class="col-md-3" > 
                                                <hr />
                                                    <img alt="image" style={{"height": "200px", "width": "100%"}} src = {productitem.image}/>
                                                    <div class="">
                                                        <h5 class="card-title" style={{"text-align": "center"}}>
                                                            {productitem.name}
                                                        </h5>
                                                        <p class="card-text">
                                                        Description: {productitem.description}
                                                        </p>
                                                        <p class="card-text">
                                                        Price: Rs {productitem.price}
                                                        </p>
                                                        <p class="card-text">
                                                        Available Quantity: {productitem.quantity}
                                                        </p>
                                                        <input type="button" class="btn btn-danger" onClick={ ()=> removeItems(productitem)}
                                                        style={{"display": "block","width":"100%;"}} value="Remove"/>
                                                    </div>
                                                </div>
                                            )
                                           
                                        })
            }
            </div>
        </div>
    </div>
</div>

    )
}
