// Angular/src/app/product/product.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../modal/product';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent implements OnInit {
  static count: any;

  constructor(private cart: CartService) { }

  _product_list : Array<Product> = [];
  _card_list : Array<Product> = [];

  
  
  ngOnInit(): void {
    
     if(localStorage.getItem("product_list")!=null){
       this.cart.product_list = JSON.parse(localStorage.getItem("product_list") || '[]');
       this._product_list = this.cart.product_list;
       console.log(this._product_list);
       
     }
    
  }
  

 addtocart(products :any){
   //let prod = 
   console.log(products.quantity);

   if(products.quantity <=0 ){
     
     alert("Sorry! Product is out of stock.");
   }
   else{
     let requiredQuan = parseInt(window.prompt("Enter Quantity: ") || '');
   let productprice_ : number = requiredQuan * parseInt(products.price);

   console.log(products.quantity);
   
   for(let ex of this.cart.cart_list ){

     if(products.id == ex.id){
       //console.log("Its pres");
       
       products.quantity = products.quantity - requiredQuan;
      
       ex.quantity += requiredQuan;
       ex.price += productprice_;
       console.log(ex.quantity);
       
       localStorage.setItem('cart',JSON.stringify(this.cart.cart_list));
       localStorage.setItem("product_list",JSON.stringify(this.cart.product_list));
       return;
     }

   }
   let prod: Product = {
    id : products.id,
    name: products.name,
    description: products.description,
    imagepath:products.imagepath,
    quantity: requiredQuan,
    price: productprice_
   }

   products.quantity = products.quantity - requiredQuan;
   console.log(products.quantity);
   
   
   this.cart.addCardList(prod);  
  
   }   
  }
  

}

 <div class="container" style="margin-top:2.5rem">
    <div class="row dd-flex ">
        <ng-container *ngFor  = "let products of _product_list">
        <div class="col-md-4">
            <div class="card px-4">
                <div class="row col-md-12">
                        <img src="{{products.imagepath}}" alt="">
                        <h2 style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;max-width: 100ch;"><strong>{{products.name}}</strong></h2>
                        <p style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;max-width: 100ch;"><strong>Description :</strong> {{products.description}}</p>
                        <p><strong>Price :</strong> {{products.price}}</p>
                        <p><strong>Quantity :</strong> {{products.quantity}}</p>
                        <div style="margin:1em;margin-left: initial;">
                        <button class="btn btn-primary" (click)=addtocart(products)>Add to cart</button>
                        </div>
                </div>
            </div>
        </div>
    </ng-container>
    </div>
</div>  
<!-- 
 <div class="vh-100 " style="margin-top: 2rem;">
    <div class="container">
        <div class="row">
        <ng-container *ngFor  = "let products of _product_list">
            <div class="col-md-4"style="margin-top: 1rem;margin-bottom:1rem">
        <div class="card p-2">
            <div class="p-info px-3 py-3">
                <div>
                    <h2 class="mb-0"><strong>{{products.name}}</strong></h2>
                </div>
                <div class="p-price d-flex flex-row"> <span>Rs.</span>
                    <h3><strong> {{products.price}}</strong></h3>
                </div>
                <div class="heart"> <i class="bx bx-heart"></i> </div>
            </div>
            <div class="text-center p-image"> <img src="{{products.imagepath}}" alt=""></div>
            <div class="p-about">
              <h4><strong>Description :</strong>{{products.description}}</h4>
              <h4><strong>Quantity :</strong>{{products.quantity}}</h4>
            </div>
            <div class="buttons d-flex flex-row gap-3 px-3"> <button class="btn btn-primary w-100" (click)=addtocart(products)>ADD TO CART</button>  </div>
        </div>
    </div>
    </ng-container>
</div>
    </div>
</div>  -->

// React/src/product.js
import React from 'react'

export const Product = (props) => {
    
    let products;
    let carts ;
    
    //Fetching Details from localstorage
    if(localStorage.getItem("products") === null)
    {
        products = [];
    }
    else
    {
       products = JSON.parse(localStorage.getItem("products"));
    }

    if(localStorage.getItem("carts") === null)
    {
        carts = [];
    }
    else
    {
       carts = JSON.parse(localStorage.getItem("carts"));
    }

    //Add product into cart
    const AddtoCart = (item) =>{
        //console.log(item.productId)
        let reqQuantity = parseInt(prompt("Please enter quantity"));
        if(reqQuantity > item.quantity)
        {
            alert("Not Enough available in stock please try again")
        }
        else if(reqQuantity > 0){
            item.quantity -= reqQuantity;
            localStorage.setItem("products",JSON.stringify(products));
            let product={
                productId:item.productId,
                name:item.name,
                image:item.image,
                description : item.description,
                quantity : reqQuantity,
                price : item.price
            };

            var temp = 0
            for(var j=0;j<carts.length;j++)
            {
                
                if(item.productId === carts[j].productId)
                {
                    carts[j].quantity += product.quantity;
                    localStorage.setItem("carts",JSON.stringify(carts));
                    props.setCarts(carts);
                    temp=1;
                    break;
                }
            
            }

            if(temp === 0)
            {
                carts.push(product);
                localStorage.setItem("carts", JSON.stringify(carts)); 
           
            }

            temp=1;
            props.setCarts(carts);
              
           
        }
        
    }

    return (

        <div className="card" style={{"width": "100%", "margin-bottom": "20px", "margin-top": "20px", "min-height": "80%;"}}>
            <div className="card-body">
                <h1 className="card-title" style={{"text-align": "center"}}>Products</h1>
                <div className="row">
                    <div className="col-md-12">
                    {
                        products.map((productitem) => {
                            return (
                                <div class="card shadow col-md-3" style={{"float":"left","margin-top":"20px","margin-left":"80px","padding":"0px","boder":"2px solid black"}}>  {/* loop here */}
                                    <img alt="" style={{"height": "200px", "width": "100%"}} src = {productitem.image.split("\\").pop()} />
                                    <div class="card-body">
                                        <h5 class="card-title" style={{"text-align": "center"}}>
                                            {productitem.name}
                                        </h5>
                                        <p class="card-text">
                                        Description: {productitem.description}
                                        </p>
                                        <p class="card-text">
                                        Price: Rs {productitem.price}
                                        </p>
                                        <p class="card-text">
                                        Available Quantity: {productitem.quantity}
                                        </p>
                                        <input type="button" class="btn btn-primary" onClick={()=>AddtoCart(productitem)}
                                        style={{"display": "block","width":"100%;"}} value="Add to Cart"/>
                                    </div>
                                </div>
                            )
                        })
                    }
                    </div>
                </div>
            </div>
        </div>
    )
}
